###
# The key used to distinguish this server.
###
key: H

###
# List of channels to send to the other servers.
###
channels:
  - Admin
  - Architect
  - Global
  - Staff
  - VIP

###
# List of channels that shouldn't be displayed from other servers.
###
ignored:
  - Example